version: '3.8'

services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pocketbase_appname_backend
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - './base/pb_data:/pb/pb_data' # Attaches pb_data to a volume named 'pocketbase-data' on your current directory
    env_file:
      - ./base/.env
